include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-frameworks-linux.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-frameworks-freebsd.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-frameworks-android.yml

stages:
- check
- build

.clazy:
  stage: check
  script:
  - zypper -qn install clazy
  - mkdir clazy
  - cd clazy
  - cmake .. -DCMAKE_CXX_COMPILER=clazy
  - make

validate_shaders:
    stage: check
    script:
    - bash scripts/validate_shaders.sh src/shaders
